<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd"
    schematypens="http://www.w3.org/2001/XMLSchema"?>

<package format="3">

  <name>rover_perception</name>
  <version>0.0.0</version>

  <description>
    Rover perception nodes including point cloud processing,
    scan fusion, and ArUco detection.
  </description>

  <maintainer email="mrmnavjet@todo.todo">
    mrmnavjet
  </maintainer>

  <license>Apache-2.0</license>

  <!-- Build system -->
  <buildtool_depend>ament_cmake</buildtool_depend>

  <!-- ROS 2 -->
  <depend>rclcpp</depend>
  <depend>rclpy</depend>

  <!-- Messages -->
  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>
  <depend>msgs</depend>

  <!-- Point cloud / TF -->
  <depend>laser_geometry</depend>
  <depend>tf2</depend>
  <depend>tf2_ros</depend>
  <depend>tf2_sensor_msgs</depend>

  <!-- Testing -->
  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>

</package>
